export const levelTracks = [
  {
    id: 'availability',
    label: 'Availability',
    description: 'Availability measures how often a service is up and usable.',
    levels: [
      {
        id: 'availability-1',
        title: '75% Availability',
        lesson: 'Availability measures how often a service is up and usable. A 75% availability target means the service needs to stay usable for most of the rolling window.',
        objective: 'Reach the finish while keeping the rolling 10s window at or above 75% availability.',
        targetLabel: 'Keep the rolling 10s window at or above 75% availability.',
        concept: 'Target: 75% availability in a rolling 10s window',
        durationSeconds: 15,
        goalDistance: 1800,
        scrollSpeed: 355,
        spawnInterval: 1.75,
        spawnVariance: 0.3,
        targetAvailability: 0.75,
        availabilityWindowSeconds: 10,
        allowedBreaches: 2,
        obstacleProfiles: [
          { width: 114, height: 82, color: '#ffb347', label: 'SHIP IT', kind: 'button' },
          { width: 76, height: 40, color: '#ff8f3c', label: 'floor plug', kind: 'power-strip' },
        ],
      },
      {
        id: 'availability-2',
        title: '85% Availability',
        lesson: 'Availability SLOs get stricter as the allowed downtime window gets smaller. At 85% availability, the service still has some room for mistakes, but repeated interruptions will push the rolling window below target quickly.',
        objective: 'Complete the aisle while keeping the rolling 10s window at or above 85% availability as hazard density increases.',
        targetLabel: 'Keep the rolling 10s window at or above 85% availability.',
        concept: 'Target: 85% availability in a rolling 10s window',
        durationSeconds: 15,
        goalDistance: 2250,
        scrollSpeed: 380,
        spawnInterval: 1.42,
        spawnVariance: 0.38,
        targetAvailability: 0.85,
        availabilityWindowSeconds: 10,
        allowedBreaches: 1,
        obstacleProfiles: [
          { width: 120, height: 85, color: '#ffb347', label: 'SHIP IT', kind: 'button' },
          { width: 84, height: 46, color: '#ff8f3c', label: 'power strip', kind: 'power-strip' },
          { width: 54, height: 76, color: '#cc6950', label: 'service cone', kind: 'cart' },
        ],
      },
      {
        id: 'availability-3',
        title: '99.9% Availability',
        lesson: 'A 99.9% availability target means downtime must be rare and brief. This concept is about protecting reliability continuously, because even one preventable outage can break the promise.',
        objective: 'Reach the finish with the rolling 10s window at or above 99.9% availability by clearing every SHIP IT button and power strip.',
        targetLabel: 'Keep the rolling 10s window at or above 99.9% availability.',
        concept: 'Target: 99.9% availability in a rolling 10s window',
        durationSeconds: 15,
        goalDistance: 2600,
        scrollSpeed: 390,
        spawnInterval: 1.28,
        spawnVariance: 0.42,
        targetAvailability: 0.999,
        availabilityWindowSeconds: 10,
        allowedBreaches: 0,
        obstacleProfiles: [
          { width: 120, height: 85, color: '#ffb347', label: 'SHIP IT', kind: 'button' },
          { width: 84, height: 46, color: '#ff8f3c', label: 'power strip', kind: 'power-strip' },
        ],
      },
    ],
  },
  {
    id: 'response-time',
    label: 'Response Time',
    description: 'Response-time SLOs measure how quickly a service answers a request.',
    levels: [
      {
        id: 'response-time-1',
        title: 'P95 under 400 ms',
        lesson: 'Response-time SLOs measure how quickly a service answers requests. A p95 target means 95% of requests must finish within the promised threshold, even if a few outliers are slower.',
        objective: 'Finish the route with 2 or fewer breaches while learning the faster pace.',
        targetLabel: 'Stay under the latency budget with no more than 2 breaches.',
        concept: 'Target: p95 under 400 ms',
        durationSeconds: 15,
        goalDistance: 2100,
        scrollSpeed: 400,
        spawnInterval: 1.35,
        spawnVariance: 0.28,
        allowedBreaches: 2,
        obstacleProfiles: [
          { width: 120, height: 28, color: '#ffbf69', label: 'cable bundle', kind: 'cable' },
          { width: 48, height: 74, color: '#d65d45', label: 'tool cart', kind: 'cart' },
        ],
      },
      {
        id: 'response-time-2',
        title: 'P95 under 300 ms',
        lesson: 'As response-time targets get tighter, teams have less room for slowdowns caused by load, queueing, or inefficient systems. The concept here is consistency, not just occasional speed.',
        objective: 'Complete the route with no more than 1 breach at the higher service speed.',
        targetLabel: 'Stay under the latency budget with no more than 1 breach.',
        concept: 'Target: p95 under 300 ms',
        durationSeconds: 15,
        goalDistance: 2550,
        scrollSpeed: 450,
        spawnInterval: 1.14,
        spawnVariance: 0.32,
        allowedBreaches: 1,
        obstacleProfiles: [
          { width: 132, height: 30, color: '#ffbf69', label: 'cable bundle', kind: 'cable' },
          { width: 56, height: 88, color: '#d65d45', label: 'tool cart', kind: 'cart' },
        ],
      },
      {
        id: 'response-time-3',
        title: 'P95 under 250 ms',
        lesson: 'A strict latency SLO such as p95 under 250 ms means the system must stay fast under pressure. The concept is that predictable performance is part of reliability, not a nice-to-have.',
        objective: 'Finish the run while keeping total breaches to 1 or fewer despite the faster aisle speed.',
        targetLabel: 'Stay under the latency budget with no more than 1 breach.',
        concept: 'Target: p95 under 250 ms',
        durationSeconds: 15,
        goalDistance: 3000,
        scrollSpeed: 500,
        spawnInterval: 1.02,
        spawnVariance: 0.34,
        allowedBreaches: 1,
        obstacleProfiles: [
          { width: 132, height: 30, color: '#ffbf69', label: 'cable bundle', kind: 'cable' },
          { width: 56, height: 88, color: '#d65d45', label: 'tool cart', kind: 'cart' },
          { width: 68, height: 90, color: '#8d6576', label: 'open rack door', kind: 'server' },
        ],
      },
    ],
  },
  {
    id: 'error-budget',
    label: 'Error Budget',
    description: 'An error budget is the amount of unreliability a service can spend while still meeting its SLO, so this track frames each breach as a scroller bug you need to smash with a hammer before it reaches players.',
    levels: [
      {
        id: 'error-budget-1',
        title: '5% Budget',
        lesson: 'An error budget is the amount of unreliability a service can spend while still meeting its SLO. Here, that allowance is framed as room to hammer scroller bugs flat before they pile up into a user-facing failure.',
        objective: 'Ship the run while hammering enough scroller bugs to stay within 4 breaches.',
        targetLabel: 'Finish the run while keeping bug-related breaches at or below 4.',
        concept: 'Target: preserve a 5% error budget',
        durationSeconds: 15,
        goalDistance: 2200,
        scrollSpeed: 390,
        spawnInterval: 1.22,
        spawnVariance: 0.24,
        allowedBreaches: 4,
        obstacleProfiles: [
          { width: 70, height: 104, color: '#8e4c3f', label: 'sticky collision bug', kind: 'cart' },
          { width: 132, height: 30, color: '#ffcf7b', label: 'scroll hitch bug', kind: 'cable' },
        ],
      },
      {
        id: 'error-budget-2',
        title: '2% Budget',
        lesson: 'When the error budget gets smaller, teams must be more selective about risk. In this pass, that means the scroller can tolerate fewer unresolved bugs before the release tradeoff turns against you, so the hammer needs to come down faster.',
        objective: 'Hold the release together with no more than 3 breaches as bug types stack up faster and demand quicker hammer hits.',
        targetLabel: 'Finish the run while keeping bug-related breaches at or below 3.',
        concept: 'Target: protect a 2% error budget',
        durationSeconds: 15,
        goalDistance: 2850,
        scrollSpeed: 455,
        spawnInterval: 1.08,
        spawnVariance: 0.26,
        allowedBreaches: 3,
        obstacleProfiles: [
          { width: 74, height: 118, color: '#8e4c3f', label: 'sticky collision bug', kind: 'cart' },
          { width: 144, height: 34, color: '#ffcf7b', label: 'scroll hitch bug', kind: 'cable' },
          { width: 62, height: 92, color: '#557b8f', label: 'render glitch bug', kind: 'server' },
        ],
      },
      {
        id: 'error-budget-3',
        title: '1% Budget',
        lesson: 'A tight error budget means there is very little room for incidents before the SLO is breached. At this point the scroller needs disciplined bug triage, because even a couple of unresolved defects can break the reliability promise if you do not hammer them out in time.',
        objective: 'Close out the run with no more than 2 breaches across collision, scrolling, and rendering bugs by smashing each one on sight.',
        targetLabel: 'Finish the run while keeping bug-related breaches at or below 2.',
        concept: 'Target: protect a 1% error budget',
        durationSeconds: 15,
        goalDistance: 3400,
        scrollSpeed: 520,
        spawnInterval: 1.02,
        spawnVariance: 0.28,
        allowedBreaches: 2,
        obstacleProfiles: [
          { width: 74, height: 118, color: '#8e4c3f', label: 'sticky collision bug', kind: 'cart' },
          { width: 144, height: 34, color: '#ffcf7b', label: 'scroll hitch bug', kind: 'cable' },
          { width: 68, height: 96, color: '#557b8f', label: 'render glitch bug', kind: 'server' },
        ],
      },
    ],
  },
];