export const levelTracks = [
  {
    id: 'availability',
    label: 'Availability',
    description: 'Availability measures how often a service is up and usable.',
    levels: [
      {
        id: 'availability-1',
        title: 'Availability I: 99.0% Uptime',
        lesson: 'Availability measures how often a service is up and usable. A 99.0% uptime SLA allows more downtime than stricter targets, but it still expects teams to prevent obvious outages.',
        objective: 'Reach the finish while keeping breaches at 2 or fewer.',
        operationalNote: 'You have some room to recover, but every loose cable still represents avoidable downtime.',
        targetLabel: 'Keep breaches at or below 2 while reaching the finish.',
        concept: 'Availability target: 99.0% uptime',
        durationSeconds: 15,
        goalDistance: 1800,
        scrollSpeed: 340,
        spawnInterval: 1.75,
        spawnVariance: 0.3,
        allowedBreaches: 2,
        obstacleProfiles: [
          { width: 106, height: 30, color: '#ffb347', label: 'power cord', kind: 'cable' },
          { width: 76, height: 40, color: '#ff8f3c', label: 'floor plug', kind: 'power-strip' },
        ],
      },
      {
        id: 'availability-2',
        title: 'Availability II: 99.5% Uptime',
        lesson: 'Availability SLAs get stricter as the allowed downtime window gets smaller. At 99.5%, even short interruptions matter because the service is expected to stay reachable almost all the time.',
        objective: 'Complete the aisle with no more than 1 breach as hazard density increases.',
        operationalNote: 'Treat repeated cable hazards as a pattern problem. Tight SLAs punish recurring mistakes.',
        targetLabel: 'Keep breaches at or below 1 while reaching the finish.',
        concept: 'Availability target: 99.5% uptime',
        durationSeconds: 15,
        goalDistance: 2250,
        scrollSpeed: 385,
        spawnInterval: 1.42,
        spawnVariance: 0.38,
        allowedBreaches: 1,
        obstacleProfiles: [
          { width: 118, height: 34, color: '#ffb347', label: 'power cord', kind: 'cable' },
          { width: 84, height: 46, color: '#ff8f3c', label: 'power strip', kind: 'power-strip' },
          { width: 54, height: 76, color: '#cc6950', label: 'service cone', kind: 'cart' },
        ],
      },
      {
        id: 'availability-3',
        title: 'Availability III: 99.9% Uptime',
        lesson: 'A 99.9% availability target means downtime must be rare and brief. This concept is about protecting reliability continuously, because even one preventable outage can break the promise.',
        objective: 'Reach the finish with zero SLA breaches by clearing every loose power cord and power strip.',
        operationalNote: 'Treat every obstacle like downtime risk. One collision means the uptime promise is already broken.',
        targetLabel: 'Keep breaches at or below 0 while reaching the finish.',
        concept: 'Availability target: 99.9% uptime',
        durationSeconds: 15,
        goalDistance: 2600,
        scrollSpeed: 415,
        spawnInterval: 1.28,
        spawnVariance: 0.42,
        allowedBreaches: 0,
        obstacleProfiles: [
          { width: 118, height: 34, color: '#ffb347', label: 'power cord', kind: 'cable' },
          { width: 84, height: 46, color: '#ff8f3c', label: 'power strip', kind: 'power-strip' },
        ],
      },
    ],
  },
  {
    id: 'response-time',
    label: 'Response Time',
    description: 'Response-time SLAs measure how quickly a service answers a request.',
    levels: [
      {
        id: 'response-time-1',
        title: 'Response Time I: P95 under 400 ms',
        lesson: 'Response-time SLAs measure how quickly a service answers requests. A p95 target means 95% of requests must finish within the promised threshold, even if a few outliers are slower.',
        objective: 'Finish the route with 2 or fewer breaches while learning the faster pace.',
        operationalNote: 'Start your jump early. Latency problems are often about reacting too late to predictable load.',
        targetLabel: 'Stay under the latency budget with no more than 2 breaches.',
        concept: 'Latency target: p95 under 400 ms',
        durationSeconds: 15,
        goalDistance: 2100,
        scrollSpeed: 400,
        spawnInterval: 1.35,
        spawnVariance: 0.28,
        allowedBreaches: 2,
        obstacleProfiles: [
          { width: 120, height: 28, color: '#ffbf69', label: 'cable bundle', kind: 'cable' },
          { width: 48, height: 74, color: '#d65d45', label: 'tool cart', kind: 'cart' },
        ],
      },
      {
        id: 'response-time-2',
        title: 'Response Time II: P95 under 300 ms',
        lesson: 'As response-time targets get tighter, teams have less room for slowdowns caused by load, queueing, or inefficient systems. The concept here is consistency, not just occasional speed.',
        objective: 'Complete the route with no more than 1 breach at the higher service speed.',
        operationalNote: 'Maintain rhythm between jumps. Consistency is what a response-time SLA actually measures.',
        targetLabel: 'Stay under the latency budget with no more than 1 breach.',
        concept: 'Latency target: p95 under 300 ms',
        durationSeconds: 15,
        goalDistance: 2550,
        scrollSpeed: 450,
        spawnInterval: 1.14,
        spawnVariance: 0.32,
        allowedBreaches: 1,
        obstacleProfiles: [
          { width: 132, height: 30, color: '#ffbf69', label: 'cable bundle', kind: 'cable' },
          { width: 56, height: 88, color: '#d65d45', label: 'tool cart', kind: 'cart' },
        ],
      },
      {
        id: 'response-time-3',
        title: 'Response Time III: P95 under 250 ms',
        lesson: 'A strict latency SLA such as p95 under 250 ms means the system must stay fast under pressure. The concept is that predictable performance is part of reliability, not a nice-to-have.',
        objective: 'Finish the run while keeping total breaches to 1 or fewer despite the faster aisle speed.',
        operationalNote: 'The route is quicker here, so jump earlier and keep enough runway before clustered hazards.',
        targetLabel: 'Stay under the latency budget with no more than 1 breach.',
        concept: 'Latency target: p95 under 250 ms',
        durationSeconds: 15,
        goalDistance: 3000,
        scrollSpeed: 500,
        spawnInterval: 1.02,
        spawnVariance: 0.34,
        allowedBreaches: 1,
        obstacleProfiles: [
          { width: 132, height: 30, color: '#ffbf69', label: 'cable bundle', kind: 'cable' },
          { width: 56, height: 88, color: '#d65d45', label: 'tool cart', kind: 'cart' },
          { width: 68, height: 90, color: '#8d6576', label: 'open rack door', kind: 'server' },
        ],
      },
    ],
  },
  {
    id: 'error-budget',
    label: 'Error Budget',
    description: 'An error budgets is the amount of unreliability a service can spend while still meeting its SLA.',
    levels: [
      {
        id: 'error-budget-1',
        title: 'Error Budget I: 5% Budget',
        lesson: 'An error budget is the amount of unreliability a service can spend while still meeting its SLA. A larger budget gives teams more freedom to experiment, but every failure still consumes that allowance.',
        objective: 'Reach the finish before spending more than 4 breaches.',
        operationalNote: 'Use the budget deliberately. It exists to absorb change, not to excuse careless runs.',
        targetLabel: 'Finish before spending more than 4 breaches.',
        concept: 'Reliability target: preserve a 5% error budget',
        durationSeconds: 15,
        goalDistance: 2200,
        scrollSpeed: 390,
        spawnInterval: 1.22,
        spawnVariance: 0.24,
        allowedBreaches: 4,
        obstacleProfiles: [
          { width: 70, height: 104, color: '#8e4c3f', label: 'battery cart', kind: 'cart' },
          { width: 132, height: 30, color: '#ffcf7b', label: 'cord snarl', kind: 'cable' },
        ],
      },
      {
        id: 'error-budget-2',
        title: 'Error Budget II: 2% Budget',
        lesson: 'When the error budget gets smaller, teams must be more selective about risk. The concept is balancing feature velocity against reliability, because failures now consume a scarcer resource.',
        objective: 'Finish the route with no more than 3 breaches as mixed hazards appear more often.',
        operationalNote: 'A tighter budget changes planning. Small mistakes that were acceptable before now become release blockers.',
        targetLabel: 'Finish before spending more than 3 breaches.',
        concept: 'Reliability target: protect a 2% error budget',
        durationSeconds: 15,
        goalDistance: 2850,
        scrollSpeed: 455,
        spawnInterval: 1.08,
        spawnVariance: 0.26,
        allowedBreaches: 3,
        obstacleProfiles: [
          { width: 74, height: 118, color: '#8e4c3f', label: 'battery cart', kind: 'cart' },
          { width: 144, height: 34, color: '#ffcf7b', label: 'cord snarl', kind: 'cable' },
          { width: 62, height: 92, color: '#557b8f', label: 'spare server', kind: 'server' },
        ],
      },
      {
        id: 'error-budget-3',
        title: 'Error Budget III: 1% Budget',
        lesson: 'A tight error budget means there is very little room for incidents before the SLA is breached. The concept is disciplined tradeoffs: if reliability is the promise, risk spending must stay controlled.',
        objective: 'Get to the finish before spending more than 2 breaches on carts, cable snarls, and spare servers.',
        operationalNote: 'An error budget gives you some room to fail, but not enough to stop respecting every hazard in the room.',
        targetLabel: 'Finish before spending more than 2 breaches.',
        concept: 'Reliability target: protect a 1% error budget',
        durationSeconds: 15,
        goalDistance: 3400,
        scrollSpeed: 520,
        spawnInterval: 1.02,
        spawnVariance: 0.28,
        allowedBreaches: 2,
        obstacleProfiles: [
          { width: 74, height: 118, color: '#8e4c3f', label: 'battery cart', kind: 'cart' },
          { width: 144, height: 34, color: '#ffcf7b', label: 'cord snarl', kind: 'cable' },
          { width: 68, height: 96, color: '#557b8f', label: 'spare server', kind: 'server' },
        ],
      },
    ],
  },
];